name: Rust Build Check
on:
  push:
    branches: [ "main" ]
    paths:
      - "ESP32-rust/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - "ESP32-rust/**"

env:
  CARGO_TERM_COLOR: always

jobs:


  
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: set toolchain
      run: rustup override set nightly

    - name: Install dependencies
      run: sh ./ESP32-rust/install_deps.sh
    
    - name: Build
      run: cd ./ESP32-rust && cargo build
