name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:


  
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions/setup-rust@v1
      with:
        rust-version: 1.54.0
    
    - name: set toolchain
      run: rustup override set nightly


    - name: Install dependencies
      run: cargo install espup && espup install
    
    - name: Build
      run: cd ESP32-rust && cargo build --verbose
      
    - name: Run tests
      run: cd ESP32-rust cargo test --verbose
